services:
  - type: web
    name: task-manager-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:password@localhost:5432/taskmanager
    healthCheckPath: /health

  - type: pserv
    name: task-manager-db
    env: postgres
    plan: free
    ipAllowList: []

